name: flutter_sheet
description: Easily change the definition (such as theme, configuration,...) for the application
version: 1.0.0+5

repository: https://github.com/sonnts996/flutter_sheet

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  meta: ^1.7.0
  copy_with_extension: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  copy_with_extension_gen: ^4.0.2
  build_runner: ^2.2.0

flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
